Repository tenable/terrascan, pull requests merged in 2022-10, with the labels that each got.

#1373 fixed typo of the function name
  pkg/policies/opa/rego/azure/azurerm_managed_disk/checkDiskEncryption.rego
Labels: policy

#1422 update rds instance cft map
  pkg/mapper/iac-providers/cft/config/db-instance.go
Labels: enhancement

#1424 Update RDS Policies
  pkg/policies/opa/rego/aws/aws_db_instance/AC_AWS_0052.json
  pkg/policies/opa/rego/aws/aws_db_instance/AWS.ADI.LM.MEDIUM.0076.json
  pkg/policies/opa/rego/aws/aws_db_instance/dbInstanceLoggingDisabled.rego
  pkg/policies/opa/rego/aws/aws_db_instance/rdsBackupDisabled.rego
  pkg/policies/opa/rego/aws/aws_db_instance/rdsLogExportDisabled.rego
Labels: new-policy, policy

#1430 Update/release command
  release_checklist.md
Labels: documentation
